[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[32mINFO    [0m pytest_operator.plugin:plugin.py:675 Connecting to existing model concierge-microk8s:testing on unspecified cloud
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHSession received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHTunneler received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[32mINFO    [0m integration.high_availability.test_crash_during_setup:test_crash_during_setup.py:30 Deploying 1 units of mysql-k8s
[32mINFO    [0m juju.model:model.py:2284 Deploying local:mysql-k8s-0
[32mINFO    [0m integration.high_availability.test_crash_during_setup:test_crash_during_setup.py:41 Waiting for single unit to be ready
[32mINFO    [0m integration.high_availability.test_crash_during_setup:test_crash_during_setup.py:47 Scaling to 3 units and wait until application enters waiting status
[32mINFO    [0m integration.high_availability.test_crash_during_setup:test_crash_during_setup.py:55 Deleting pod
[32mINFO    [0m integration.high_availability.test_crash_during_setup:test_crash_during_setup.py:59 Waiting until cluster is fully active
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [executing] maintenance: 
  mysql-k8s/2 [executing] maintenance: Initialising mysqld
  mysql-k8s/1 [executing] maintenance: Initialising mysqld
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] maintenance: offline
  mysql-k8s/2 [executing] waiting: waiting to get cluster primary from peers
  mysql-k8s/1 [executing] waiting: waiting to get cluster primary from peers
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] active: Primary
  mysql-k8s/2 [idle] waiting: waiting to join the cluster
  mysql-k8s/1 [executing] maintenance: joining the cluster
[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Model status:

Model    Controller          Cloud/Region        Version  SLA          Timestamp
testing  concierge-microk8s  microk8s/localhost  3.6.8    unsupported  01:49:31Z

App        Version                  Status   Scale  Charm      Channel  Rev  Address         Exposed  Message
mysql-k8s  8.0.42-0ubuntu0.22.04.2  waiting      3  mysql-k8s             0  10.152.183.199  no       waiting for units to settle down

Unit          Workload  Agent      Address       Ports  Message
mysql-k8s/0*  error     idle       10.1.112.206         hook failed: "update-status"
mysql-k8s/1   active    executing  10.1.112.205         
mysql-k8s/2   waiting   idle       10.1.112.204         waiting to join the cluster

[32mINFO    [0m pytest_operator.plugin:plugin.py:796 Juju error logs:

unit-mysql-k8s-0: 01:48:38 ERROR unit.mysql-k8s/0.juju-log Cluster upgrade failed, ensure pre-upgrade checks are ran first.
unit-mysql-k8s-0: 01:49:30 ERROR unit.mysql-k8s/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/charm.py", line 1102, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/relations/mysql_provider.py", line 255, in _on_update_status
    self.charm._mysql.update_endpoints(DB_RELATION_NAME)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/mysql_k8s_helpers.py", line 906, in update_endpoints
    rw_endpoints, ro_endpoints, offline = self.charm.get_cluster_endpoints(relation_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/mysql/v0/mysql.py", line 803, in get_cluster_endpoints
    address = f"{self.get_unit_address(unit_labels[k], relation_name)}:3306"
KeyError: 'mysql-k8s-1.mysql-k8s-endpoints.testing.svc.cluster.local.:3306'
unit-mysql-k8s-0: 01:49:31 ERROR juju.worker.uniter.operation hook "update-status" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Forgetting main...