[32mINFO    [0m integration.backups:backups.py:125 Creating backup
[32mINFO    [0m integration.backups:backups.py:129 Creating test data 1
[32mINFO    [0m mysql.connector:authentication.py:66 package: mysql.connector.plugins
[32mINFO    [0m mysql.connector:authentication.py:67 plugin_name: caching_sha2_password
[32mINFO    [0m mysql.connector:authentication.py:71 AUTHENTICATION_PLUGIN_CLASS: MySQLCachingSHA2PasswordAuthPlugin
[32mINFO    [0m integration.backups:backups.py:145 Creating test data 2
[32mINFO    [0m integration.backups:backups.py:157 Scaling down to 1 unit
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s (waiting for exactly 1 units, current : 3)
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s (waiting for exactly 1 units, current : 3)
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] active: 
[32mINFO    [0m integration.backups:backups.py:169 Restoring backup 2025-04-19T01:31:47Z with bad restore-to-time parameter
[32mINFO    [0m integration.backups:backups.py:178 Restoring backup 2025-04-19T01:31:47Z with year_before restore-to-time parameter
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] blocked: Failed to restore point-in-time-recovery to the 2024-04-19 01:32:06
  s3-integrator/0 [idle] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] blocked: Failed to restore point-in-time-recovery to the 2024-04-19 01:32:06
[32mINFO    [0m integration.backups:backups.py:190 Restoring backup 2025-04-19T01:31:47Z with year_after restore-to-time parameter
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] blocked: Failed to restore point-in-time-recovery to the 2026-04-19 01:32:06
  s3-integrator/0 [idle] active: 
[32mINFO    [0m integration.backups:backups.py:202 Restoring backup 2025-04-19T01:31:47Z with actual restore-to-time parameter
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [executing] blocked: Failed to restore point-in-time-recovery to the 2025-04-19 01:32:06
  s3-integrator/0 [idle] active: 
[32mINFO    [0m integration.backups:backups.py:214 Restoring backup 2025-04-19T01:31:47Z with restore-to-time=latest parameter
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] blocked: Failed to restore point-in-time-recovery to the latest
  s3-integrator/0 [idle] active: 
[32mINFO    [0m integration.backups:backups.py:38 Cleaning backups from cloud buckets
[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Model status:

Model    Controller          Cloud/Region        Version  SLA          Timestamp
testing  concierge-microk8s  microk8s/localhost  3.6.5    unsupported  01:36:14Z

App            Version                  Status   Scale  Charm          Channel        Rev  Address         Exposed  Message
mysql-k8s      8.0.41-0ubuntu0.22.04.1  waiting      1  mysql-k8s                       0  10.152.183.145  no       installing agent
s3-integrator                           active       1  s3-integrator  latest/stable  145  10.152.183.79   no       

Unit              Workload  Agent  Address       Ports  Message
mysql-k8s/0*      blocked   idle   10.1.226.204         failed to recover cluster.
s3-integrator/0*  active    idle   10.1.226.200         

[32mINFO    [0m pytest_operator.plugin:plugin.py:796 Juju error logs:

unit-mysql-k8s-1: 01:29:21 ERROR unit.mysql-k8s/1.juju-log upgrade:3: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-1: 01:29:23 ERROR unit.mysql-k8s/1.juju-log upgrade:3: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-1: 01:29:25 ERROR unit.mysql-k8s/1.juju-log upgrade:3: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-1: 01:29:27 ERROR unit.mysql-k8s/1.juju-log upgrade:3: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-1: 01:29:29 ERROR unit.mysql-k8s/1.juju-log upgrade:3: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-1: 01:29:31 ERROR unit.mysql-k8s/1.juju-log upgrade:3: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-0: 01:29:41 ERROR unit.mysql-k8s/0.juju-log upgrade:3: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-0: 01:29:43 ERROR unit.mysql-k8s/0.juju-log upgrade:3: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-0: 01:29:45 ERROR unit.mysql-k8s/0.juju-log upgrade:3: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-0: 01:29:54 ERROR unit.mysql-k8s/0.juju-log upgrade:3: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-0: 01:29:56 ERROR unit.mysql-k8s/0.juju-log upgrade:3: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-0: 01:29:58 ERROR unit.mysql-k8s/0.juju-log upgrade:3: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-0: 01:31:55 ERROR unit.mysql-k8s/0.juju-log get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-0: 01:31:57 ERROR unit.mysql-k8s/0.juju-log get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-0: 01:31:59 ERROR unit.mysql-k8s/0.juju-log get_unit_address: unit DNS domain name is not fully propagated yet, trying again

[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Forgetting main...