[32mINFO    [0m pytest_operator.plugin:plugin.py:675 Connecting to existing model microk8s-localhost:test on unspecified cloud
[32mINFO    [0m integration.high_availability.conftest:conftest.py:68 Deploying mysql-k8s and scaling to 3 units
[32mINFO    [0m juju.model:model.py:2284 Deploying local:mysql-k8s-0
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [allocating] waiting: installing agent
  mysql-k8s/1 [allocating] waiting: installing agent
  mysql-k8s/2 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [executing] maintenance: installing charm software
  mysql-k8s/1 [executing] maintenance: installing charm software
  mysql-k8s/2 [executing] maintenance: installing charm software
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] waiting: waiting to get cluster primary from peers
  mysql-k8s/1 [idle] waiting: waiting to get cluster primary from peers
  mysql-k8s/2 [executing] active: Primary
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [executing] maintenance: joining the cluster
  mysql-k8s/1 [executing] active: 
  mysql-k8s/2 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/1 [idle] active: 
  mysql-k8s/2 [idle] active: Primary
[32mINFO    [0m integration.high_availability.conftest:conftest.py:71 Deploying mysql-test-app
[32mINFO    [0m juju.model:model.py:2284 Deploying ch:amd64/jammy/mysql-test-app-63
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-test-app/0 [allocating] waiting: installing agent
[32mINFO    [0m integration.high_availability.conftest:conftest.py:74 Relating mysql-k8s with mysql-test-app
[33mWARNING [0m juju.model:model.py:1666 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] active: 
  mysql-k8s/1 [idle] active: 
  mysql-k8s/2 [idle] active: Primary
  mysql-test-app/0 [idle] waiting: 
[32mINFO    [0m integration.high_availability.conftest:conftest.py:29 Clearing continuous writes
[32mINFO    [0m integration.high_availability.conftest:conftest.py:31 Starting continuous writes
[32mINFO    [0m integration.conftest:conftest.py:20 Getting credentials for the MySQL cluster
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:124 Ensuring that all units continuous writes incrementing
[32mINFO    [0m mysql.connector:authentication.py:66 package: mysql.connector.plugins
[32mINFO    [0m mysql.connector:authentication.py:67 plugin_name: caching_sha2_password
[32mINFO    [0m mysql.connector:authentication.py:71 AUTHENTICATION_PLUGIN_CLASS: MySQLCachingSHA2PasswordAuthPlugin
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:505 max_written_value=893 on unit mysql-k8s/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:505 max_written_value=903 on unit mysql-k8s/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:505 max_written_value=911 on unit mysql-k8s/2
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:135 Sending SIGSTOP to unit mysql-k8s/2
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:158 Waiting for new primary to be elected
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:172 Ensuring all remaining units continuous writes incrementing
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:505 max_written_value=1247 on unit mysql-k8s/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:505 max_written_value=1247 on unit mysql-k8s/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:505 max_written_value=1247 on unit mysql-k8s/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:505 max_written_value=1247 on unit mysql-k8s/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:505 max_written_value=1247 on unit mysql-k8s/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:505 max_written_value=1247 on unit mysql-k8s/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:505 max_written_value=1247 on unit mysql-k8s/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:505 max_written_value=1247 on unit mysql-k8s/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:505 max_written_value=1247 on unit mysql-k8s/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:505 max_written_value=1247 on unit mysql-k8s/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:505 max_written_value=1278 on unit mysql-k8s/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:505 max_written_value=1289 on unit mysql-k8s/1
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:181 Sending SIGCONT to mysql-k8s/2
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] active: Primary
  mysql-k8s/1 [idle] active: 
  mysql-k8s/2 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] active: Primary
  mysql-k8s/1 [idle] active: 
  mysql-k8s/2 [idle] maintenance: error
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] active: Primary
  mysql-k8s/1 [idle] active: 
  mysql-k8s/2 [idle] maintenance: error
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:224 Ensuring that there are 3 online mysql members
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:229 Ensure all units continuous writes incrementing
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:505 max_written_value=9759 on unit mysql-k8s/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:505 max_written_value=9770 on unit mysql-k8s/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:505 max_written_value=9780 on unit mysql-k8s/2
[32mINFO    [0m integration.high_availability.conftest:conftest.py:36 Clearing continuous writes
[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.6.2    unsupported  01:36:46Z

App             Version                  Status  Scale  Charm           Channel      Rev  Address         Exposed  Message
mysql-k8s       8.0.39-0ubuntu0.22.04.1  active      3  mysql-k8s                      0  10.152.183.104  no       
mysql-test-app  0.0.2                    active      1  mysql-test-app  latest/edge   63  10.152.183.89   no       Last written value=7078

Unit               Workload  Agent  Address      Ports  Message
mysql-k8s/0        active    idle   10.1.232.11         Primary
mysql-k8s/1        active    idle   10.1.232.13         
mysql-k8s/2*       active    idle   10.1.232.12         
mysql-test-app/0*  active    idle   10.1.232.14         Last written value=7078

[32mINFO    [0m pytest_operator.plugin:plugin.py:796 Juju error logs:

unit-mysql-k8s-0: 01:32:12 ERROR unit.mysql-k8s/0.juju-log Failed to execute mysql-shell command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/mysql_k8s_helpers.py", line 644, in _run_mysqlsh_script
    stdout, _ = process.wait_output()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1771, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['timeout', '30', '/usr/bin/mysqlsh', '--passwords-from-stdin', '--uri=serverconfig@mysql-k8s-0.mysql-k8s-endpoints.test.svc.cluster.local:33062', '--python', '--verbose=0', '-c', "shell.options.set('useWizards', False)\nprint('###')\ncluster = dba.get_cluster('test_cluster')\nprint(cluster.status({'extended': False}))"], stdout="\x1b[1mPlease provide the password for 'serverconfig@mysql-k8s-0.mysql-k8s-endpoints.test.svc.cluster.local:33062': \x1b[0m###\n", stderr='Cannot set LC_ALL to locale en_US.UTF-8: No such file or directory\n\x1b[33mWARNING: \x1b[0mError connecting to Cluster: MYSQLSH 51004: Unable to connect to the primary member of the Cluster: \'The provided URI uses the X protocol, which is not supported by this command.\'\nRetrying getCluster() using a secondary member\nNo PRIMARY member found for cluster \'test_cluster\'\nNo PRIMARY member found for cluster \'test_cluster\'\nTraceback (most recent call last):\n  File "<string>", line 4, in <module>\nmysqlsh.Error: Shell Error (51603): Cluster.status: Could not connect to PRIMARY of Primary Cluster \'test_cluster\'\n'
unit-mysql-k8s-0: 01:32:12 ERROR unit.mysql-k8s/0.juju-log Failed to get cluster status for test_cluster
unit-mysql-k8s-2: 01:35:11 ERROR unit.mysql-k8s/2.juju-log Failed to execute MySQL cli command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/mysql_k8s_helpers.py", line 692, in _run_mysqlcli_script
    stdout, _ = process.wait_output()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1766, in wait_output
    exit_code: int = self._wait()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1727, in _wait
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Execute command "/usr/bin/mysql" (timed out after 10s: context deadline exceeded)
----- Logs from task 0 -----
2025-01-26T01:35:11Z ERROR timed out after 10s: context deadline exceeded
-----
unit-mysql-k8s-2: 01:35:11 ERROR unit.mysql-k8s/2.juju-log Failed to get member state: mysqld daemon is down
unit-mysql-k8s-2: 01:35:23 ERROR unit.mysql-k8s/2.juju-log Failed to execute mysql-shell command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/mysql_k8s_helpers.py", line 644, in _run_mysqlsh_script
    stdout, _ = process.wait_output()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1771, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['/usr/bin/mysqlsh', '--passwords-from-stdin', '--uri=serverconfig@mysql-k8s-2.mysql-k8s-endpoints.test.svc.cluster.local:33062', '--python', '--verbose=0', '-c', "shell.options.set('useWizards', False)\nprint('###')\nshell.connect_to_primary()\nprimary_address = shell.parse_uri(session.uri)['host']\nprint(f'<PRIMARY_ADDRESS>{primary_address}</PRIMARY_ADDRESS>')"], stdout="\x1b[1mPlease provide the password for 'serverconfig@mysql-k8s-2.mysql-k8s-endpoints.test.svc.cluster.local:33062': \x1b[0m###\n", stderr='Cannot set LC_ALL to locale en_US.UTF-8: No such file or directory\nTraceback (most recent call last):\n  File "<string>", line 3, in <module>\nmysqlsh.Error: Shell Error (51002): Shell.connect_to_primary: Group replication does not seem to be active in instance \'mysql-k8s-2.mysql-k8s-endpoints.test.svc.cluster.local:3306\'\n'

[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Forgetting main...