[32mINFO    [0m integration.test_saturate_max_connections:test_saturate_max_connections.py:71 Running action to get app connection data
[32mINFO    [0m integration.test_saturate_max_connections:test_saturate_max_connections.py:80 Creating 10 connections
[32mINFO    [0m mysql.connector:__init__.py:149 package: mysql.connector.plugins
[32mINFO    [0m mysql.connector:__init__.py:150 plugin_name: caching_sha2_password
[32mINFO    [0m mysql.connector:__init__.py:154 AUTHENTICATION_PLUGIN_CLASS: MySQLCachingSHA2PasswordAuthPlugin
[32mINFO    [0m integration.test_saturate_max_connections:test_saturate_max_connections.py:84 Ensure all connections are established
[32mINFO    [0m integration.test_saturate_max_connections:test_saturate_max_connections.py:90 Ensure no more client connections are possible
[32mINFO    [0m integration.test_saturate_max_connections:test_saturate_max_connections.py:96 Get cluster status while connections are saturated
[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Model status:

Model    Controller          Cloud/Region        Version  SLA          Timestamp
testing  concierge-microk8s  microk8s/localhost  3.6.9    unsupported  02:07:29Z

App    Version                  Status   Scale  Charm           Channel      Rev  Address         Exposed  Message
app    0.0.2                    waiting      1  mysql-test-app  latest/edge   82  10.152.183.82   no       installing agent
mysql  8.0.42-0ubuntu0.22.04.2  active       1  mysql-k8s                      0  10.152.183.123  no       Primary

Unit      Workload  Agent      Address       Ports  Message
app/0*    active    idle       10.1.248.142         
mysql/0*  active    executing  10.1.248.141         Primary

[32mINFO    [0m pytest_operator.plugin:plugin.py:796 Juju error logs:

unit-mysql-0: 02:06:55 ERROR unit.mysql/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/lib/python3.10/site-packages/ops/model.py", line 3187, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-mysql-0/secret-get', '--label', 'database-peers.mysql.app', '--format=json')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-0/charm/src/charm.py", line 1127, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 516, in _emit
    self.framework.reemit()
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 870, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-0/charm/src/relations/mysql_root.py", line 101, in _on_leader_elected
    not self.charm._is_peer_data_set
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/mysql/v0/mysql.py", line 796, in _is_peer_data_set
    and self.get_secret("app", ROOT_PASSWORD_KEY)
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/mysql/v0/mysql.py", line 918, in get_secret
    not (value := self.peer_relation_data(scope).fetch_my_relation_field(peers.id, key))
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1397, in fetch_my_relation_field
    if relation_data := self.fetch_my_relation_data([relation_id], [field], relation_name):
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1386, in fetch_my_relation_data
    data[relation.id] = self._fetch_my_specific_relation_data(relation, fields)
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 536, in wrapper
    return f(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2344, in _fetch_my_specific_relation_data
    self.component, self.secret_fields, relation, fields
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1981, in secret_fields
    self.static_secret_fields if self.static_secret_fields else self.current_secret_fields
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2000, in current_secret_fields
    if content := self._get_group_secret_contents(relation, group):
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2331, in _get_group_secret_contents
    result = super()._get_group_secret_contents(relation, group, secret_fields)
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1123, in _get_group_secret_contents
    if (secret := self._get_relation_secret(relation.id, group)) and (
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 508, in wrapper
    return f(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2318, in _get_relation_secret
    return self.secrets.get(
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 812, in get
    if secret.meta:
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 642, in meta
    self._secret_meta = self._model.get_secret(label=self.label)
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/lib/python3.10/site-packages/ops/model.py", line 291, in get_secret
    content = self._backend.secret_get(id=id, label=label)
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/lib/python3.10/site-packages/ops/model.py", line 3552, in secret_get
    result = self._run('secret-get', *args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/lib/python3.10/site-packages/ops/model.py", line 3189, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR cannot ensure service account "unit-mysql-0": rpc error: code = Unknown desc = exec (try: 500): database is locked

unit-mysql-0: 02:06:56 ERROR juju.worker.uniter.operation hook "mysql-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-0: 02:06:56 ERROR juju.worker.uniter pebble poll failed for container "mysql": failed to send pebble-ready event: hook failed

[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Forgetting main...