[32mINFO    [0m integration.conftest:conftest.py:31 Getting credentials for the MySQL cluster
[32mINFO    [0m integration.high_availability.test_upgrade_from_stable:test_upgrade_from_stable.py:98 Refresh the charm
[32mINFO    [0m integration.high_availability.test_upgrade_from_stable:test_upgrade_from_stable.py:101 Wait for upgrade to complete on first upgrading unit
[32mINFO    [0m integration.high_availability.test_upgrade_from_stable:test_upgrade_from_stable.py:112 Resume upgrade
[32mINFO    [0m httpx:_client.py:1026 HTTP Request: GET https://10.1.0.20:16443/apis/apps/v1/namespaces/testing/statefulsets/mysql-k8s "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1026 HTTP Request: GET https://10.1.0.20:16443/apis/apps/v1/namespaces/testing/statefulsets/mysql-k8s "HTTP/1.1 200 OK"
[32mINFO    [0m integration.high_availability.test_upgrade_from_stable:test_upgrade_from_stable.py:125 Wait for upgrade to complete
[32mINFO    [0m integration.high_availability.test_upgrade_from_stable:test_upgrade_from_stable.py:131 Ensure continuous_writes
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=22493 on unit mysql-k8s/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=22493 on unit mysql-k8s/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=22539 on unit mysql-k8s/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=22550 on unit mysql-k8s/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=22557 on unit mysql-k8s/2
[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Model status:

Model    Controller          Cloud/Region        Version  SLA          Timestamp
testing  concierge-microk8s  microk8s/localhost  3.6.9    unsupported  01:47:16Z

App        Version                  Status  Scale  Charm           Channel      Rev  Address        Exposed  Message
mysql-k8s  8.0.42-0ubuntu0.22.04.2  active      3  mysql-k8s                      0  10.152.183.33  no       
test-app   0.0.2                    active      1  mysql-test-app  latest/edge   85  10.152.183.99  no       Last written value=22493

Unit          Workload  Agent  Address      Ports  Message
mysql-k8s/0   active    idle   10.1.242.81         
mysql-k8s/1   active    idle   10.1.242.80         Primary
mysql-k8s/2*  active    idle   10.1.242.79         
test-app/0*   active    idle   10.1.242.72         Last written value=22493

[32mINFO    [0m pytest_operator.plugin:plugin.py:796 Juju error logs:

unit-mysql-k8s-1: 01:39:42 ERROR unit.mysql-k8s/1.juju-log database-peers:1: Cannot connect to the pebble in the mysql container to check binlogs collector
unit-mysql-k8s-1: 01:39:42 ERROR unit.mysql-k8s/1.juju-log database-peers:1: Failed to reconcile binlogs collection during peer relation event
unit-mysql-k8s-2: 01:39:42 ERROR unit.mysql-k8s/2.juju-log database-peers:1: Cannot connect to the pebble in the mysql container to check binlogs collector
unit-mysql-k8s-2: 01:39:42 ERROR unit.mysql-k8s/2.juju-log database-peers:1: Failed to reconcile binlogs collection during peer relation event
unit-mysql-k8s-0: 01:39:42 ERROR unit.mysql-k8s/0.juju-log database-peers:1: Cannot connect to the pebble in the mysql container to check binlogs collector
unit-mysql-k8s-0: 01:39:42 ERROR unit.mysql-k8s/0.juju-log database-peers:1: Failed to reconcile binlogs collection during peer relation event
unit-mysql-k8s-0: 01:39:46 ERROR unit.mysql-k8s/0.juju-log database-peers:1: Cannot connect to the pebble in the mysql container to check binlogs collector
unit-mysql-k8s-0: 01:39:46 ERROR unit.mysql-k8s/0.juju-log database-peers:1: Failed to reconcile binlogs collection during peer relation event
unit-mysql-k8s-1: 01:39:47 ERROR unit.mysql-k8s/1.juju-log database-peers:1: Cannot connect to the pebble in the mysql container to check binlogs collector
unit-mysql-k8s-1: 01:39:47 ERROR unit.mysql-k8s/1.juju-log database-peers:1: Failed to reconcile binlogs collection during peer relation event
unit-mysql-k8s-2: 01:39:47 ERROR unit.mysql-k8s/2.juju-log database-peers:1: Cannot connect to the pebble in the mysql container to check binlogs collector
unit-mysql-k8s-2: 01:39:47 ERROR unit.mysql-k8s/2.juju-log database-peers:1: Failed to reconcile binlogs collection during peer relation event
unit-mysql-k8s-2: 01:39:50 ERROR unit.mysql-k8s/2.juju-log database-peers:1: Cannot connect to the pebble in the mysql container to check binlogs collector
unit-mysql-k8s-2: 01:39:50 ERROR unit.mysql-k8s/2.juju-log database-peers:1: Failed to reconcile binlogs collection during peer relation event
unit-mysql-k8s-0: 01:39:51 ERROR unit.mysql-k8s/0.juju-log database-peers:1: Cannot connect to the pebble in the mysql container to check binlogs collector
unit-mysql-k8s-0: 01:39:51 ERROR unit.mysql-k8s/0.juju-log database-peers:1: Failed to reconcile binlogs collection during peer relation event
unit-mysql-k8s-0: 01:39:53 ERROR unit.mysql-k8s/0.juju-log database-peers:1: Cannot connect to the pebble in the mysql container to check binlogs collector
unit-mysql-k8s-0: 01:39:53 ERROR unit.mysql-k8s/0.juju-log database-peers:1: Failed to reconcile binlogs collection during peer relation event
unit-mysql-k8s-1: 01:39:53 ERROR unit.mysql-k8s/1.juju-log database-peers:1: Cannot connect to the pebble in the mysql container to check binlogs collector
unit-mysql-k8s-1: 01:39:53 ERROR unit.mysql-k8s/1.juju-log database-peers:1: Failed to reconcile binlogs collection during peer relation event

[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Forgetting main...